batch: 64
epochs: 3
embeddingDimEncoder: 512
embeddingDimDecoder: 100
hiddendDimDecoder: 512
hiddendDimEncoder: 512
n_layersEncoder: 5
n_layersDecoder: 1
dropout_Encoder: 0.3
dropout_Decoder: 0.3
lr: 1e-3
